development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: webchat_production

#url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>